/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

//@ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually

algoSidebar: [
    {
      type: 'doc',
      id: 'intro', // Ensure you have an intro.md in /docs
      label: '🚀 Start Here',
    },
 {
  type: 'category',
  label: 'Linear Foundation',
  collapsed: false,
  // This makes clicking "Linear Foundation" open an index page
  link: { type: 'generated-index' }, 
  items: [
    {
      type: 'category',
      label: 'Two Pointers',
      link: {
        type: 'doc',
        id: 'linear-foundation/two-pointers/intro',
      },
      items: [
        'linear-foundation/two-pointers/trapping-rain-water',
        'linear-foundation/two-pointers/cracking-the-3sum-challenge',
        'linear-foundation/two-pointers/two-sum-input-array-is-sorted',
        'linear-foundation/two-pointers/two-sum-array-is-not-sorted',
        'linear-foundation/two-pointers/two-sum-array-is-not-sorted',
        'linear-foundation/two-pointers/valid-palindrome-with-one-deletion',
        'linear-foundation/two-pointers/boats-to-save-people',
        'linear-foundation/two-pointers/di-string-match',
      ],
    },
    {
      type: 'category',
      label: 'Sliding Window',
      link: {
        type: 'doc',
        id: 'linear-foundation/sliding-window/intro',
      },
      items: [
        // 'linear-foundation/prefix-sum/pii-audit-prefix-sums-in-strings',
      ],
    },
    {
      type: 'category',
      label: 'Prefix Sum',
      // Clicking the "Prefix Sum" folder will now open the intro file.
      link: {
        type: 'doc',
        id: 'linear-foundation/prefix-sum/intro',
      },
      items: [
        // We don't need to list 'intro' here again if it's the category link, 
        // but you can if you want it visible in the list too.
        'linear-foundation/prefix-sum/pii-audit-prefix-sums-in-strings',
      ],
    },
  ],
},
    {
      type: 'category',
      label: 'Phase 2. Logic of Organization',
      collapsed: true,
      items: [
        'Phase 2. Logic of Organization/binary-search', 
        'Phase 2. Logic of Organization/recursion-backtracking',
        'Phase 2. Logic of Organization/sorting',
      ],
    },
    {
      type: 'category',
      label: 'Phase 3. The Connected Web',
      collapsed: true,
      items: [
        'Phase 3. The Connected Web/trees',
        'Phase 3. The Connected Web/graphs',
        'Phase 3. The Connected Web/heaps',
      ],
    },
    {
      type: 'category',
      label: 'Phase 4. The Optimization Peak',
      collapsed: true,
      items: [
        'Phase 4. The Optimization Peak/dynamic-programming',
        'Phase 4. The Optimization Peak/tries',
        'Phase 4. The Optimization Peak/bit-manipulation',
      ],
    },
  ],
};

export default sidebars;
