/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

//@ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually

  algoSidebar: [
    {
      type: 'doc',
      id: 'intro', // Ensure you have an intro.md in /docs
      label: '🚀 Start Here',
    },
 {
      type: 'category',
      label: 'Phase 1. Linear Foundation',
      collapsed: false,
      items: [
        'Phase 1. Linear Foundation/sliding-window',
        'Phase 1. Linear Foundation/two-pointers',
        'Phase 1. Linear Foundation/prefix-sum',
      ],
    },
    {
      type: 'category',
      label: 'Phase 2. Logic of Organization',
      collapsed: true,
      items: [
        'Phase 2. Logic of Organization/binary-search', // Note: Matching your error log (missing 'n' at end)
        'Phase 2. Logic of Organization/recursion-backtracking',
        'Phase 2. Logic of Organization/sorting',
      ],
    },
    {
      type: 'category',
      label: 'Phase 3. The Connected Web',
      collapsed: true,
      items: [
        'Phase 3. The Connected Web/trees',
        'Phase 3. The Connected Web/graphs',
        'Phase 3. The Connected Web/heaps',
      ],
    },
    {
      type: 'category',
      label: 'Phase 4. The Optimization Peak',
      collapsed: true,
      items: [
        'Phase 4. The Optimization Peak/dynamic-programming',
        'Phase 4. The Optimization Peak/tries',
        'Phase 4. The Optimization Peak/bit-manipulation',
      ],
    },
  ],
};

export default sidebars;
