/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

//@ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually

algoSidebar: [
    {
      type: 'doc',
      id: 'intro', // Ensure you have an intro.md in /docs
      label: '🚀 Start Here',
    },
 {
  type: 'category',
  label: 'Linear Foundation',
  collapsed: false,
  // This makes clicking "Linear Foundation" open an index page
  link: { type: 'generated-index' }, 
  items: [
    {
      type: 'category',
      label: 'Two Pointers',
      link: {
        type: 'doc',
        id: 'linear-foundation/two-pointers/intro',
      },
      items: [
        'linear-foundation/two-pointers/trapping-rain-water',
        'linear-foundation/two-pointers/cracking-the-3sum-challenge',
        'linear-foundation/two-pointers/two-sum-input-array-is-sorted',
        'linear-foundation/two-pointers/two-sum-array-is-not-sorted',
        'linear-foundation/two-pointers/two-sum-array-is-not-sorted',
        'linear-foundation/two-pointers/valid-palindrome-with-one-deletion',
        'linear-foundation/two-pointers/boats-to-save-people',
        'linear-foundation/two-pointers/di-string-match',

        'linear-foundation/two-pointers/shortest-distance-to-a-character',
       // 'linear-foundation/two-pointers/sort-colors',
       // 'linear-foundation/two-pointers/maximum-water-trapped-between-walls',
      ],
    },
    {
      type: 'category',
      label: 'Sliding Window',
      link: {
        type: 'doc',
        id: 'linear-foundation/sliding-window/intro',
      },
      items: [
        // 'linear-foundation/prefix-sum/pii-audit-prefix-sums-in-strings',
      ],
    },
    {
      type: 'category',
      label: 'Prefix Sum',
      // Clicking the "Prefix Sum" folder will now open the intro file.
      link: {
        type: 'doc',
        id: 'linear-foundation/prefix-sum/intro',
      },
      items: [
        // We don't need to list 'intro' here again if it's the category link, 
        // but you can if you want it visible in the list too.
        'linear-foundation/prefix-sum/pii-audit-prefix-sums-in-strings',
      ],
    },

        {
      type: 'category',
      label: 'Intervals',
      link: {
        type: 'doc',
        id: 'linear-foundation/intervals/intro',
      },
      items: [
         'linear-foundation/intervals/merge-overlapping-intervals',

        // 'linear-foundation/intervals/meeting-calendar',
        // 'linear-foundation/intervals/minimum-meeting-rooms-needed',
        // 'linear-foundation/intervals/disjoint-intervals',
      ],
    },

  ],
},
    {
      type: 'category',
      label: 'Logic of Organization',
      collapsed: true,
      link: { type: 'generated-index' },
      items: [
            {
      type: 'category',
      label: 'Binary Search',
      link: {
        type: 'doc',
        id: 'logic-of-organization/binary-search/intro',
      },
      items: [
       // 'logic-of-organization/binary-search/find-an-element-in-the-rotated-array',
       // 'logic-of-organization/binary-search/search-insert-position',
       // 'logic-of-organization/binary-search/search-in-rotated-sorted-array',
      ],
    },

    {
      type: 'category',
      label: 'Recursion',
      link: {
        type: 'doc',
        id: 'logic-of-organization/recursion/intro',
      },
      items: [
       // 'logic-of-organization/recursion/carrying-the-digits',
       // 'logic-of-organization/recursion/staircase-climbing-combinations',
       // 'logic-of-organization/recursion/add-binary',
      ],
    },

    {
      type: 'category',
      label: 'Sorting',
      link: {
        type: 'doc',
        id: 'logic-of-organization/sorting/intro',
      },
      items: [
       // 'logic-of-organization/sorting/data-merging',
       // 'logic-of-organization/sorting/selection-sort',
       // 'logic-of-organization/sorting/insertion-sort',
       // 'logic-of-organization/sorting/quick-sort',
       // 'logic-of-organization/sorting/bubble-sort',
       // 'logic-of-organization/sorting/next-permutation',
      ],
    },

      ],
    },
    {
      type: 'category',
      label: 'The Connected Web',
      collapsed: true,
      link: { type: 'generated-index' },
      items: [
        {
      type: 'category',
      label: 'Graph',
      link: {
        type: 'doc',
        id: 'the-connected-web/graph/intro',
      },
      items: [
       'the-connected-web/graph/breadth-first-search',
       'the-connected-web/graph/depth-first-search',
      ],
    },
        'the-connected-web/heaps',
      ],
    },
    {
      type: 'category',
      label: 'Phase 4. The Optimization Peak',
      collapsed: true,
      items: [
        'the-optimization-peak/dynamic-programming',
        'the-optimization-peak/tries',
        'the-optimization-peak/bit-manipulation',
      ],
    },
  ],
};

export default sidebars;
